[tool.black]
line-length = 79
target-version = ['py37']
exclude = '''
/(
    \.eggs|
    \.git|
    \.hg|
    \.mypy_cache|
    \.tox|
    \.venv|
    \.idea|
    \.pytest_cache|
    __pycache__|
    build|
    dist
)/
'''
