name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run linter
        run: |
          flake8 .

      - name: Run formatter
        run: |
          black --check .

      - name: Run tests
        run: |
          pytest
